{
    "_meta_name": "Solarized",

    "background_color":        "#fdf6e3",
    "text_color":               "#586e75",
    "secondary_text_color":     "#93a1a1",
    "border_color":             "#d3cbb7",

    "button_background_color":  "#eee8d5",
    "button_text_color":        "#586e75",

    "input_background_color":   "#ffffff",
    "input_text_color":         "#073642",

    "accent_color":             "#268bd2",

    "log_background_color":     "#002b36",
    "log_text_color":           "#839496"
}
